services:
  commander:
    build: .
    restart: unless-stopped
    volumes:
      - ./stars.db:/app/stars.db
      - ./cache.db:/app/cache.db
      - ./credentials.py:/app/credentials.py
      - ./services/ebay/brands.py:/app/services/ebay/brands.py
    environment:
      - PYTHONUNBUFFERED=1
